# Generated by Django 4.2.5 on 2025-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('admin_profile_update', 'Admin Updated Profile'), ('part_create', 'Created Part'), ('part_update', 'Updated Part'), ('part_delete', 'Deleted Part'), ('part_mark', 'Marked Part'), ('part_unmark', 'Unmarked Part'), ('clear_all_marks', 'Cleared All Marks'), ('document_upload', 'Uploaded Document'), ('document_update', 'Updated Document'), ('document_delete', 'Deleted Document'), ('csv_import', 'Imported CSV'), ('csv_export', 'Exported CSV')], max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
