# Generated by Django 4.2.5 on 2025-03-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['level', 'position', 'code']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='doc_reference',
            field=models.CharField(blank=True, help_text='Reference documentation', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fabricant',
            field=models.CharField(blank=True, help_text='Manufacturer/brand', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='full_code',
            field=models.CharField(blank=True, help_text='Full hierarchical code including parent codes', max_length=150),
        ),
        migrations.AddField(
            model_name='equipment',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Hierarchy level (1=root, 2=child, etc.)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(help_text='Equipment code (without parent prefix)', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order within same level'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('parent', 'code')},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='related_parts',
        ),
    ]
