# Generated by Django 4.2.5 on 2025-02-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='codification_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Codification hierarchy level'),
        ),
        migrations.AddField(
            model_name='part',
            name='component_code',
            field=models.CharField(blank=True, help_text='Level 3 component code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='equipment_code',
            field=models.CharField(blank=True, help_text='Equipment codification code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='subcomponent_code',
            field=models.CharField(blank=True, help_text='Level 4 subcomponent code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='subsystem_code',
            field=models.CharField(blank=True, help_text='Level 2 subsystem code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='system_code',
            field=models.CharField(blank=True, help_text='Level 1 system code', max_length=20, null=True),
        ),
    ]
